# Generated by Django 2.0.4 on 2018-05-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Imię')),
                ('surname', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('attending', models.CharField(choices=[('Yes', 'Tak'), ('No', 'Nie'), ('Maybe', 'Nie określono')], default='Maybe', max_length=5, verbose_name='Będę na weselu')),
                ('wants_bus', models.BooleanField(default=False, help_text='Zapewniamy dojazd spod kościoła na salę weselną zaraz po mszy\n        i z powrotem do Poznania na koniec wesela (koło 4 w nocy).')),
                ('is_vegetarian', models.BooleanField(default=False, help_text='Informacja ta pomoże nam przy wyborze menu')),
                ('gift', models.CharField(max_length=50, verbose_name='Prezent')),
                ('comments', models.CharField(max_length=200, verbose_name='Dodatkowy komentarz')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
