# Generated by Django 2.0.4 on 2018-05-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Informacja ta pomoże nam przy wyborze menu', verbose_name='Preferuję dania wegetariańskie'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wants_bus',
            field=models.BooleanField(default=False, help_text='Zapewniamy dojazd spod kościoła na salę weselną zaraz po mszy\n        i z powrotem do Poznania na koniec wesela (koło 4 w nocy).', verbose_name='Chcę jechać autobusem'),
        ),
    ]
