# Generated by Django 2.0.4 on 2018-05-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0002_auto_20180516_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='comments',
            field=models.TextField(max_length=200, verbose_name='Dodatkowy komentarz'),
        ),
    ]
