# Generated by Django 2.0.4 on 2018-05-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0003_auto_20180516_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='comments',
            field=models.TextField(blank=True, max_length=200, verbose_name='Dodatkowy komentarz'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gift',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Prezent'),
        ),
    ]
