# Generated by Django 2.0.4 on 2018-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0007_page_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default=None, max_length=15, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
