# Generated by Django 2.0.4 on 2018-06-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0009_auto_20180612_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='gift',
            field=models.CharField(blank=True, help_text='W celu uniknięcia powtarzania się upominków,\n                     możesz wpisać tutaj swój prezent.', max_length=50, verbose_name='Prezent'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wants_bus',
            field=models.BooleanField(default=False, help_text='Zapewniamy dojazd spod kościoła na salę weselną zaraz po mszy\n                     i z powrotem do Poznania na koniec wesela (koło 4 w nocy).', verbose_name='Chcę jechać autobusem'),
        ),
    ]
