# Generated by Django 2.0.4 on 2018-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0010_auto_20180613_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
    ]
