# Generated by Django 2.1.3 on 2018-12-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0012_gift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='gift',
        ),
    ]
