# Generated by Django 2.1.3 on 2018-12-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0013_auto_20181222_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='is_reserved',
        ),
    ]
