# Generated by Django 2.1.3 on 2019-01-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0014_remove_gift_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
