# Generated by Django 2.1.3 on 2019-01-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0015_gift_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_accompanying_person',
            field=models.BooleanField(default=False),
        ),
    ]
