# Generated by Django 2.1.3 on 2019-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_guests', '0016_guest_is_accompanying_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending_afters',
            field=models.CharField(choices=[('Yes', 'Tak'), ('No', 'Nie'), ('Maybe', 'Nie określono')], default='Maybe', max_length=5, verbose_name='Będę na poprawinach'),
        ),
        migrations.AddField(
            model_name='guest',
            name='eligible_for_afters',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='wants_bus',
            field=models.BooleanField(default=False, help_text='Więcej informacji w zakładce dojazd.', verbose_name='Chcę jechać busem'),
        ),
    ]
